name: amadeo
description: Amadeo is a starter/cookbook Flutter project for Commercio.network.

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  asn1lib: ^0.6.5
  basic_utils: ^2.5.7
  bloc: ^6.0.0
  commercio_ui: ^0.1.0
  cupertino_icons: ^0.1.3
  encrypt: ^4.0.2
  flutter_bloc: ^6.0.1
  pointycastle: ^1.0.2
  qr_flutter: ^3.2.0
  lumberdash: ^2.1.1
  colorize_lumberdash: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  pedantic: ^1.9.0
  mockito: ^4.1.1
  test_coverage: ^0.4.3

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
          style: normal
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700

  assets:
    - document.txt
    - id_keys.json
