name: amadeo_flutter
description: Amadeo is a tarter/cookbook Flutter projec for Commercio.network.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.5.0
  bloc: ^4.0.0
  commercio_ui:
    git:
      url: git@github.com:commercionetwork/CommercioUI.git
      ref: fix/add-docs
  commerciosdk: ^2.1.0
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.1
  log_4_dart_2: ^0.4.0
  qr_flutter: ^3.2.0
  sacco: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  lint: ^1.2.0
  mockito: ^4.1.1
  test_coverage: ^0.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/document.txt
