name: amadeo
description: Amadeo is a starter/cookbook Flutter project for Commercio.network.
publish_to: 'none'

version: 0.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_commercio_ui:
    git:
      url: https://github.com/commercionetwork/CommercioUI.git
      path: packages/flutter_commercio_ui
      ref: null-safety
  colorize_lumberdash: ^3.0.0
  cupertino_icons: ^1.0.3
  lumberdash: ^3.0.0
  qr_flutter: ^4.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  mocktail: ^0.1.4

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
          style: normal
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700

  assets:
    - document.txt
    - id_keys.json
