name: amadeo
description: Amadeo is a starter/cookbook Flutter projec for Commercio.network.

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  asn1lib: ^0.6.5
  basic_utils: ^2.5.5
  bloc: ^5.0.1
  commercio_ui:
    git:
      url: https://github.com/commercionetwork/CommercioUI.git
      ref: master
  commerciosdk:
    git:
      url: https://github.com/pasqenr/commercio-sdk.dart.git
      ref: master
  cupertino_icons: ^0.1.3
  encrypt: ^4.0.2
  flutter_bloc: ^5.0.1
  pointycastle: ^1.0.2
  qr_flutter: ^3.2.0
  sacco:
    git:
      url: https://github.com/pasqenr/sacco.dart
      ref: master

  lumberdash: ^2.1.1
  colorize_lumberdash: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  pedantic: ^1.9.0
  mockito: ^4.1.1
  test_coverage: ^0.4.3

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
          style: normal
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700

  assets:
    - document.txt
    - id_keys.json
